# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1706eafab8e3077a0cf5bda8fcc3be2eb3f7d7476f79d3da5a7200d0a404e84a465222cdabb75f6a73d9415f82ecc9d24359b2ea09818b25b75dd97a3cce597f

test:
  secret_key_base: 0f4b1420d79b7a45a070366d9f3bd2806de3c204d60df4e89deb0230710e218a08b99581dc1dc4788c6354ff213a8205d949f498258c35c8195faf30eef861c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
